---
language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode
  - rbx

bundler_args: --path vendor/bundle

script:
  - bundle exec rake test

addons:
  code_climate:
    repo_token: 1f1d11d604da3092e424824c006ae74d0ff882f4cd4cab51c12201fb7c461b8a
